#!/bin/bash

if [ -z "$(xdotool search --name @hal)" ]; then
	echo "Empty"
	xdotool key "ctrl+shift+t"
	sleep 1
	xdotool getactivewindow set_window --name CFN-HAL
fi
wid="$(xdotool search --name @hal)"
echo "Window ID: $wid"
for i in $(seq 1 3);
do
    #xdotool windowactivate $wid key "ctrl+shift+plus"
    xdotool windowactivate $wid key KP_Enter
done
xdotool keyup --window $wid a type "ssh -o ProxyCommand='ssh etsai@ssh.bnl.gov nc -w 10 %h %p' -X -t etsai@130.199.242.229 'cd ~ && exec bash -l'"
xdotool key KP_Enter

